name: JSON updater

on:
  schedule:
    - cron: "0 0 * * *"
    
  workflow_dispatch:

jobs:
  DL:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update the danged JSON
        run: |
          cd $GITHUB_WORKSPACE
          rm circuitsv2.json
          curl -O "https://raw.githubusercontent.com/tyleo-rec/CircuitsV2Resources/master/misc/circuitsv2.json"
          git push
